### ISSUE TITLE
week 03 - day 03 - Final

### ISSUE THREAD

**Issue by gstark** [KillahBea/assignments#11]
# Prove yourself, warrior!

This assignment will pull together all the skills and ideas that you have learned for the past three weeks. This project is a bit bigger than usual and will challenge you on the core concepts we have learned over unit-i.

For this assignment, you will solve three code katas, and recreate a simple website that uses an API for the data. [This is the website](http://sdg-astro-club.surge.sh/) you will make. This website should be responsive and as close as you can make it.

Since this is a more significant assignment, the pacing is critical.

## Objectives

- Demonstrate basic knowledge of some programming ideas
- using HTML, CSS and JavaScript re-create a simple website
- Recreate [http://sdg-astro-club.surge.sh/](http://sdg-astro-club.surge.sh/)

## Requirements

- Complete the three selected code katas
- Create an SDG Astro Club website using https://sdg-astro-api.herokuapp.com for the data

## Deliverables

- a [gist](https://gist.github.com/) containing the solutions to all three katas
- GitHub repository containing the HTML, JS, and CSS the website
- a URL to the deployed site.

### Explorer Mode

- [x] complete the following katas
  - https://www.codewars.com/kata/filter-out-the-geese
  - https://www.codewars.com/kata/beginner-lost-without-a-map/train/javascript
  - https://www.codewars.com/kata/you-only-need-one-beginner
- [x] replicate this site exactly (as close as possible) [http://sdg-astro-club.surge.sh/](http://sdg-astro-club.surge.sh/)
  - You should pull data from the API [https://sdg-astro-api.herokuapp.com](https://sdg-astro-api.herokuapp.com)
    - use [https://sdg-astro-api.herokuapp.com/api/Nasa/apod](https://sdg-astro-api.herokuapp.com/api/Nasa/apod) for the NASA picture of the day
    - use [https://sdg-astro-api.herokuapp.com/api/SpaceX/launches/upcoming](https://sdg-astro-api.herokuapp.com/api/SpaceX/launches/upcoming) for the upcoming launch data.
- [ ] deploy your site

## Advice

- Take this in small steps. I would do this in the following order: Katas, HTML, CSS, Picture of the day, and then Upcoming Launches.
- Commit early and commit often.
- Use Font-awesome for the icons. Attach this script to the head of your page, and you will be able to use the CSS to create the icons

````html
<script
  defer
  src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"
  integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0"
  crossorigin="anonymous"
></script>
```
````

**Comment by KillahBea** [comment]
https://gist.github.com/KillahBea/9a9e2343b6e457c16260438a83e864cd

**Comment by KillahBea** [comment]
Lost without a map - https://gist.github.com/KillahBea/219da3ab80a0078a1cbfd3e865466ac5

**Comment by KillahBea** [comment]
https://gist.github.com/KillahBea/a19c9b660db044b48113fe01723c976e

**Comment by KillahBea** [comment]
https://github.com/KillahBea/unit-1-final

The timer isn't functioning, I welcome feedback on how to get the blasted "explore your universe" text to stick and for some silly reason the bottom made with love @ SDG isn't right. It's simple, I know.

**Comment by mdewey** [comment]
So for your "explore your universe" There shouldn't be an `img` tag, but your HTML should look like this:

``` html
<section class="hero-image">
    <h1 class="text-primary-color">Explore your universe.</h1>
</section>
```

and the class `hero-image` has its property of `background-image` set dynamically. 

But overall good job!

**Comment by mdewey** [comment]
Your homework was marked: **Acceptable**

![Not Bad](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26e47afe0d88e75d27a696b1e3719f5c026a93c5/not-bad.gif)
> &ldquo;Not Bad&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/6)**__
