### ISSUE TITLE
career support - resumes - Build your Resume

### ISSUE THREAD

**Issue by ktrammell95** [KillahBea/assignments#21]
Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [ ] Portfolio link

## Summary 
- [ ]  Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” simply use a headline that encapsulates your credentials.

## Skills 
- [ ]  You’ll want to incorporate the right keywords so that your resume is optimized for application tracking systems

## Professional experience
- [ ]  Focus on your accomplishments rather than your day-to-day responsibilities

## Education
- [x]  Simply write where you went college and your degree.
- [x]  It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [x]  Volunteering and community service

## Due Date: Wednesday, June 19th
- [x]  Upload or submit a link to your resume for review.

**Comment by KillahBea** [comment]
[Bea Resume 2.pdf](https://github.com/KillahBea/assignments/files/3298220/Bea.Resume.2.pdf)

**Comment by ktrammell95** [comment]
You have great info but you aren't highlighting your dev stuff at all. I know you are still learning and maybe not 100% sure what direction you want to go in but they are still useful to help push you into a new career path once you figure that out.

Look at your education and think about if they all get you where you want to go or not, do you need them if the answer is no. 

If you want to stick to 1 page, which I think is good for you...  add more about SDG under experience and think about taking off or summarizing anything that kicks you on to two pages

I played with the layout a bit to give you some ideas, https://docs.google.com/document/d/10Q7IqWvXB6GPNfWln1ESXNk4uAZELOroJastjWzcRAw/edit?usp=sharing

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6653a5b4c8e877384d759556a53bfc97521ca49f/giphy-17.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/82)**__
